### PR TITLE
Fix unbootable systems with LUKS

### PR DESCRIPTION
**Pull request by cat-master21**
Fixes disk decryption for people who installed RL with LUKS encryption. Before the initrfs would have issues:
Screenshot from 2023-08-20 13-49-35

### CODE REVIEW

**Comment by cat-master21** [comment]
Yeah this fixes it now test image https://github.com/rhino-linux/os/actions/runs/5919746755 
Screenshot from 2023-08-20 16-42-25

**Comment by ajstrongdev** [comment]
@cat-master21 Can i merge?

**Comment by ajstrongdev** [comment]
@cat-master21 Can you be a bit more descriptive on what this PR is fixing?

**Comment by cat-master21** [comment]
Yep @ajstrongdev this works/fixes on UEFI and BIOS.

**Comment by ajstrongdev** [comment]
Closes #46

**Comment by ajstrongdev** [comment]
Closes #38

**Pull request merged**
