### PR TITLE
make an interactive script for terraforming ubuntu -> rhino

### PR DESCRIPTION
**Pull request by oklopfer**
also works for changing suites on already rhino systems
```bash
bash -c "$(curl -fsSL https://raw.githubusercontent.com/oklopfer/rhino-os/main/ub2r.sh)"
```
can test with this ^^

### CODE REVIEW

**Comment by ajstrongdev** [comment]
Can confirm the script works, and it works well. I personally tested it in a 24.04 docker container, having installed rhino-server-core.
If possible can we look into the possability of utilising `pacstall -PI` for all installs so the user is not prompted, and having all Rhino Linux specific prompts be at the start of the script, have it save the answer in a variable and then continue from there.

By doing this we force the user to only sit through ~10 seconds of prompts and decisions, after that they can make a cup of tea or something while their OS transforms into Rhino Linux

**Review by ajstrongdev — CHANGES_REQUESTED** [review]
Postential changes as laid out in the last comment?

**Comment by oklopfer** [comment]
> Postential changes as laid out in the last comment?

all easily doable - should pacstall install also be done promptlessly?

**Comment by ajstrongdev** [comment]
> Can confirm the script works, and it works well. I personally tested it in a 24.04 docker container, having installed rhino-server-core. If possible can we look into the possability of utilising `pacstall -PI` for all installs so the user is not prompted, and having all Rhino Linux specific prompts be at the start of the script, have it save the answer in a variable and then continue from there.
> 
> By doing this we force the user to only sit through ~10 seconds of prompts and decisions, after that they can make a cup of tea or something while their OS transforms into Rhino Linux



> > Postential changes as laid out in the last comment?
> 
> all easily doable - should pacstall install also be done promptlessly?

Imo yes.

**Comment by oklopfer** [comment]
need to make it so:
1. it doesnt let the script be run as root
2. raspberry pi does not get provided the kernel options
3. maybe actually inverse of 1? who knows

**Comment by oklopfer** [comment]
Nala re-install has a bug, need to fix it with an apt pin in pacstall. 

rhino-setup install has a bug due to some stray variable not being unset. Needs to be fixed in pacstall but need to have a workaround for this script.

**Comment by oklopfer** [comment]
Package install should check if the packages are installed already before running -PI on them again

**Comment by ajstrongdev** [comment]
All my tests succeeded. Approved.

**Comment by oklopfer** [comment]
Screenshot 2024-03-11 at 3 31 48 PM

full install is still experiencing issues

**Pull request merged**
